### ISSUE TITLE
Patches that have been saved with previous version, crash on opening.

### ISSUE THREAD

**Issue by bbdomestique** [stoermelder/vcvrack-packtau#16]
First, thank you so much for making this resource available.  I use your modules in all my patches.  I updated to the latest version and now all the patches I have that use pack 1 modules crash when I try to open them.  Sometimes rack will say on opening "Could not find module Stoermelder-P1/StripBlock."  Once I hit ok, it crashes.  I'm happy to send the .vcv file if that helps.  I'm running windows 11.  Happy to give more info if that helps.

**Comment by stoermelder** [comment]
Thanks for reporting. Strip-Block has not been officially released and is not included in the plugin distributed in the VCV Library - I'm not sure I will ever include it. It is still in the development build though.
Still, it should not crash. Please send me one of you patch (not too big if possible) and I'll check.

**Comment by bbdomestique** [comment]
[sax setup 221120.zip](https://github.com/stoermelder/vcvrack-packone/files/10086601/sax.setup.221120.zip)

all of my patches are pretty big but let me know if this is too big.  I have another computer that still runs the patches; I could thin them out and resave them so they are smaller if that is helpful.

**Comment by bbdomestique** [comment]
just to be clear my other computer will run them because i havent updated pack 1 (or vcv rack pro to 2.2.0)

**Comment by stoermelder** [comment]
I transfered the issue to PackTau as it was cause by the RF module.
Should be fixed in aa711161ea64223177d49af78579b8d56e5d9ed9.

**Comment by bbdomestique** [comment]
awesome! This stuff is right at the threshold of my understanding.  Can I just update packTau and the issue should be resolved?

**Comment by stoermelder** [comment]
Yes, here a new builds:
https://github.com/stoermelder/vcvrack-packtau/releases/tag/Nightly

**Comment by bbdomestique** [comment]
Thank you so much!!

**Comment by bbdomestique** [comment]
that fix made that particular patch work but the rest of them still crash.  It makes me think it could be something else that doesn't have anything to do with your pack1 or packtau because none of the other patches give me any info before they crash.  In case it is and you don't mind taking another look I'm attaching another patch file that still crashes.  Thanks again.

[midi controller v3 ded.zip](https://github.com/stoermelder/vcvrack-packtau/files/10086948/midi.controller.v3.ded.zip)

**Comment by stoermelder** [comment]
I fixed the crash with module RF but you really shouldn't use it. It was highly experimental in Rack v1 and completely untested in Rack v2.
